<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="/style/style.css" />
    <script src="/jquery.js"></script>
    <script src="/stars/Tycho2.js" type="text/javascript"></script>
    <script src="/astro.js" type="text/javascript"></script>
    <script src="/mchp.js" type="text/javascript"></script>

</head>
<body>
    <div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
    <div id="page">
    <div style="padding:0 0 5px 5px"><img src="/mchp.gif" alt="Microchip" /></div>

    <div id="title"><div class="right"></div><span id="hello">&nbsp;</span></div>
    <div id="menu">
        <a href="/index.htm">Обзор</a>
        <a href="/auth.htm">Идентификация</a>
        <a href="/cookies.htm">Cookies</a>
        <!--a href="/upload.htm">File Uploads</a-->
        <a href="/protect/config.htm">Настройка сети</a>
		<a href="/protect/monty.htm">Настройка монтировки</a>
    </div>